on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Checkout
      uses: actions/checkout@v3
    - run: npm install
    - run: npm run build --if-present
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAMER }}
        key: ${{ secrets.KEY }}
        source: "apps/web/dist"
        target: ${{ secrets.WEB_TARGET }}
        strip_components: 3

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAMER }}
        key: ${{ secrets.KEY }}
        source: "apps/api/dist,apps/api/package.json"
        target: ${{ secrets.API_TARGET }}
        strip_components: 2
