on:
  workflow_dispatch:
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        cache: npm
        node-version: 18
    - name: Checkout
      uses: actions/checkout@v3
    - run: npm install
    - run: npm run build
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        source: "apps/api/dist,apps/web/dist"
        target: "shouzhuabing"
