on:
  workflow_dispatch:
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker Buildx Bake
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shouzhuabing:latest

    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v3.0.2
      with:
        # The HTTP URI of the webhook endpoint to invoke
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        # json | form-urlencoded | json-extended
        webhook_type: json
        data: ${{ steps.docker_build.outputs }}
        
